### ISSUE TITLE
Link to Stata icons for mimetype association do not work.

### ISSUE THREAD

**Issue by cpz-research** [acarril/acarril.github.io#8]
**Describe the bug**
https://acarril.github.io/posts/install-stata-linux

The link here doesn't work anymore: 

First download this tarball with Stata icons and extract it wherever you like.

**Comment by acarril** [comment]
Fixed in 54d442b116ae2ddc1314958ad5194939be8b8156. Thanks for flagging it!

**Comment by cpz-research** [comment]
Thank you for the fast reply!
